# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='schedule.DaySchedule', verbose_name='Пятница')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Group', verbose_name='Группа')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='schedule.DaySchedule', verbose_name='Понедельник')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='schedule.DaySchedule', verbose_name='Суббота')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='schedule.DaySchedule', verbose_name='Четверг')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='schedule.DaySchedule', verbose_name='Вторник')),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='schedule.DaySchedule', verbose_name='Среда')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
            },
        ),
        migrations.CreateModel(
            name='TeachLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Cabinet', verbose_name='Кабинет')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Lesson', verbose_name='Преподает')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='schedule.TeachLesson', verbose_name='5 пара'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four', to='schedule.TeachLesson', verbose_name='4 пара'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='schedule.TeachLesson', verbose_name='1 пара'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='schedule.TeachLesson', verbose_name='3 пара'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='schedule.TeachLesson', verbose_name='2 пара'),
        ),
    ]
