# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0003_auto_20170328_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='chedule.DayChedule', verbose_name='Пятница')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chedule.TeachLesson', verbose_name='Группа')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='chedule.DayChedule', verbose_name='Понедельник')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='chedule.DayChedule', verbose_name='Суббота')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='chedule.DayChedule', verbose_name='Четверг')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='chedule.DayChedule', verbose_name='Вторник')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='chedule.DayChedule', verbose_name='Среда')),
            ],
        ),
    ]
