# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chedule', '0004_groupchedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchedule',
            options={'verbose_name': 'Расписание группы', 'verbose_name_plural': 'Расписания групп'},
        ),
        migrations.AlterField(
            model_name='groupchedule',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.Group', verbose_name='Группа'),
        ),
    ]
