# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_cabinet_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachlesson',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='teachlesson',
            name='lessons',
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.DeleteModel(
            name='TeachLesson',
        ),
    ]
