# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20170328_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
